### ISSUE TITLE
update backend for conversion tracking in google analytics/adwords/etc

### ISSUE THREAD

**Issue by bulletfactory** [raintank/website-v2#25]
The request is to update the backend of our signup form to track user sessions via cookies, so that we can pass the "source" and "keyword" params, among others, through to the typeform page and know when signups come from adwords, remarketing, twitter/facebook, website, etc.

**Comment by woodsaj** [comment]
@bulletfactory  where is this data going? do you want it sent to Intercom?

**Comment by bulletfactory** [comment]
the original purpose was to have this information in google analytics and have 3 different conversion goal types - direct signup, signup from an adword campaign/other ad campaign and signup from social. 

Passing the info to intercom would be great, but seeing % of conversion compared to all web traffic, or target web traffic (ie social or adwords traffic) in google analytics to gauge ROI is what we're after.

The problem we were running into was that the same exact form (w/ no params) used all over the site was being sent to intercom, then auto redirected to 3rd party system that we couldn't effectively segment after submission - i knew there was a signup, but couldn't tell from where.

**Comment by woodsaj** [comment]
what is currently in place was never designed for GA, it was designed for integration with intercom.
The various signup forms scattered throughout the site already include a "source" field that is sent with the signup to Intercom. This source field tracks from which page the "signup button" was pressed.

this new change now enables us to track the query params that are used in campaign links.  Currently we are sending these along with the existing "source" field to intercom.

We can easily enough use these same tracked params when redirecting to the typeform form page.

my questions are:
1) do you also want to include the existing "source" field that is used to track from which page a user has clicked the signup form.
2) to help keep things clear, can the tracking query params (eg, "source", "keywords") be prefixed with "tracking_" before being included in url for the typeform form page being redirected to? this will help limit some possible malicous attack vectors.

**Comment by bulletfactory** [comment]
We don't need to also add "source" to the redirect. that is only to see which signup button they clicked, which I'm happy to leave in intercom.

Totally cool with the tracking param being prefixed w. "tracking_"

**Comment by nopzor1200** [comment]
I *think* we can get what we want from Google Analytics just by making sure that the GA tag is included in all our pages, and by setting up the right goals in GA itself, right?

The GA stuff is unrelated to this particular issue (which is all about storing key/values about a session upon entry). 

These key/values are currently only used for Intercom but could be sent anywhere as part of any action the user performs on the site. It just so happens that some of the information in the key/value will correspond to Google Adwords related things.

Is this right? I'd like to understand. I could be totally incorrect.

**Comment by bulletfactory** [comment]
Yes, you are correct. We needed to pass the landing page source into
typeform, so that I can match it to the various campaigns.
ie: a signup that entered the site at http://raintank.io/?source=twitter
will count as a twitter conversion only so we can accurately segment
conversions.

**Comment by woodsaj** [comment]
@bulletfactory has this change been deployed to production? want me to?

**Comment by bulletfactory** [comment]
This has been deployed to production. The new data is tracking the 3
existing goals correctly in GA.

a signup from twitter (anyone who signs up after reaching this page
raintank.io/?source=twitter)
a signup from adwords (raintank.io/?source=cpc)
a direct signup (a signup w/ no "source="

We can create any "source" variable we want to track future goals, these
were just the first 2.

Thanks,
t
